#!/bin/zsh
# print 2018 DYJets_DL
# python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18NanoAODv7-Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/NANOAODSIM' --simultaneous 4 --nThreads 4 --write --prefetch --redir root://cms-xrd-global.cern.ch/ --outdir /eos/cms/store/user/nmangane/NANOv7_bookkeeping/skims/2018/DYJets_DL
# print 2018 DYJets_DL-HT100 --keep LHE_HT genWeight nElectron Electron_pt Electron_cutBased Electron_eta Electron_ip3d Electron_dz Electron_jetIdx nMuon Muon_pt Muon_eta Muon_looseId Muon_pfIsoId Muon_ip3d Muon_dz Muon_jetIdx nJet Jet_pt Jet_eta Jet_jetId
# python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/DYJetsToLL_M-50_HT-100to200_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIIAutumn18NanoAODv7-Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/NANOAODSIM' --simultaneous 4 --nThreads 4 --write --prefetch --redir root://cms-xrd-global.cern.ch/ --outdir /eos/cms/store/user/nmangane/NANOv7_bookkeeping/skims/2018/DYJets_DL-HT100 --keep LHE_HT genWeight nElectron Electron_pt Electron_cutBased Electron_eta Electron_ip3d Electron_dz Electron_jetIdx nMuon Muon_pt Muon_eta Muon_looseId Muon_pfIsoId Muon_ip3d Muon_dz Muon_jetIdx nJet Jet_pt Jet_eta Jet_jetId
# print 2018 DYJets_DL-HT200
# python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/DYJetsToLL_M-50_HT-200to400_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIIAutumn18NanoAODv7-Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/NANOAODSIM' --simultaneous 4 --nThreads 4 --write --prefetch --redir root://cms-xrd-global.cern.ch/ --outdir /eos/cms/store/user/nmangane/NANOv7_bookkeeping/skims/2018/DYJets_DL-HT200 --keep LHE_HT genWeight nElectron Electron_pt Electron_cutBased Electron_eta Electron_ip3d Electron_dz Electron_jetIdx nMuon Muon_pt Muon_eta Muon_looseId Muon_pfIsoId Muon_ip3d Muon_dz Muon_jetIdx nJet Jet_pt Jet_eta Jet_jetId
# print 2018 DYJets_DL-HT400
# python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/DYJetsToLL_M-50_HT-400to600_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIIAutumn18NanoAODv7-Nano02Apr2020_EXT2_102X_upgrade2018_realistic_v21-v1/NANOAODSIM' --simultaneous 4 --nThreads 4 --write --prefetch --redir root://cms-xrd-global.cern.ch/ --outdir /eos/cms/store/user/nmangane/NANOv7_bookkeeping/skims/2018/DYJets_DL-HT400 --keep LHE_HT genWeight nElectron Electron_pt Electron_cutBased Electron_eta Electron_ip3d Electron_dz Electron_jetIdx nMuon Muon_pt Muon_eta Muon_looseId Muon_pfIsoId Muon_ip3d Muon_dz Muon_jetIdx nJet Jet_pt Jet_eta Jet_jetId
print 2018 DYJets_DL-HT600
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/DYJetsToLL_M-50_HT-600to800_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIIAutumn18NanoAODv7-Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/NANOAODSIM' --simultaneous 4 --nThreads 4 --write --prefetch --redir root://cms-xrd-global.cern.ch/ --outdir /eos/cms/store/user/nmangane/NANOv7_bookkeeping/skims/2018/DYJets_DL-HT600 --keep LHE_HT genWeight nElectron Electron_pt Electron_cutBased Electron_eta Electron_ip3d Electron_dz Electron_jetIdx nMuon Muon_pt Muon_eta Muon_looseId Muon_pfIsoId Muon_ip3d Muon_dz Muon_jetIdx nJet Jet_pt Jet_eta Jet_jetId
print 2018 DYJets_DL-HT800
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/DYJetsToLL_M-50_HT-800to1200_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIIAutumn18NanoAODv7-Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/NANOAODSIM' --simultaneous 4 --nThreads 4 --write --prefetch --redir root://cms-xrd-global.cern.ch/ --outdir /eos/cms/store/user/nmangane/NANOv7_bookkeeping/skims/2018/DYJets_DL-HT800 --keep LHE_HT genWeight nElectron Electron_pt Electron_cutBased Electron_eta Electron_ip3d Electron_dz Electron_jetIdx nMuon Muon_pt Muon_eta Muon_looseId Muon_pfIsoId Muon_ip3d Muon_dz Muon_jetIdx nJet Jet_pt Jet_eta Jet_jetId
print 2018 DYJets_DL-HT1200
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/DYJetsToLL_M-50_HT-1200to2500_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIIAutumn18NanoAODv7-Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/NANOAODSIM' --simultaneous 4 --nThreads 4 --write --prefetch --redir root://cms-xrd-global.cern.ch/ --outdir /eos/cms/store/user/nmangane/NANOv7_bookkeeping/skims/2018/DYJets_DL-HT1200 --keep LHE_HT genWeight nElectron Electron_pt Electron_cutBased Electron_eta Electron_ip3d Electron_dz Electron_jetIdx nMuon Muon_pt Muon_eta Muon_looseId Muon_pfIsoId Muon_ip3d Muon_dz Muon_jetIdx nJet Jet_pt Jet_eta Jet_jetId
# print 2018 DYJets_DL-HT2500
# python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/DYJetsToLL_M-50_HT-2500toInf_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIIAutumn18NanoAODv7-Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/NANOAODSIM' --simultaneous 4 --nThreads 4 --write --prefetch --redir root://cms-xrd-global.cern.ch/ --outdir /eos/cms/store/user/nmangane/NANOv7_bookkeeping/skims/2018/DYJets_DL-HT2500  --keep LHE_HT genWeight nElectron Electron_pt Electron_cutBased Electron_eta Electron_ip3d Electron_dz Electron_jetIdx nMuon Muon_pt Muon_eta Muon_looseId Muon_pfIsoId Muon_ip3d Muon_dz Muon_jetIdx nJet Jet_pt Jet_eta Jet_jetId
