#!/bin/zsh
print 2017 ElMu ST_tW
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_top_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'ElMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tW/ElMu/
print 2017 ElMu ST_tbarW
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'ElMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tbarW/ElMu/
print 2017 ElMu ST_tW-NoFHad
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'ElMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tW-NoFHad/ElMu/
print 2017 ElMu ST_tbarW-NoFHad
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'ElMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tbarW-NoFHad/ElMu/
print 2017 ElMu ElMu_B
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__ElMu_B.txt' --filter 'ElMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ElMu_B/ElMu/
print 2017 ElMu ElMu_C
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__ElMu_C.txt' --filter 'ElMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ElMu_C/ElMu/
print 2017 ElMu ElMu_D
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__ElMu_D.txt' --filter 'ElMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ElMu_D/ElMu/
print 2017 ElMu ElMu_E
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__ElMu_E.txt' --filter 'ElMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ElMu_E/ElMu/
print 2017 ElMu ElMu_F
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__ElMu_F.txt' --filter 'ElMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ElMu_F/ElMu/
print 2017 MuMu ST_tW
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_top_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'MuMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tW/MuMu/
print 2017 MuMu ST_tbarW
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'MuMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tbarW/MuMu/
print 2017 MuMu ST_tW-NoFHad
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'MuMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tW-NoFHad/MuMu/
print 2017 MuMu ST_tbarW-NoFHad
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'MuMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tbarW-NoFHad/MuMu/
print 2017 MuMu MuMu_B
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__MuMu_B.txt' --filter 'MuMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/MuMu_B/MuMu/
print 2017 MuMu MuMu_C
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__MuMu_C.txt' --filter 'MuMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/MuMu_C/MuMu/
print 2017 MuMu MuMu_D
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__MuMu_D.txt' --filter 'MuMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/MuMu_D/MuMu/
print 2017 MuMu MuMu_E
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__MuMu_E.txt' --filter 'MuMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/MuMu_E/MuMu/
print 2017 MuMu MuMu_F
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__MuMu_F.txt' --filter 'MuMu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/MuMu_F/MuMu/
print 2017 ElEl ST_tW
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_top_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'ElEl>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tW/ElEl/
print 2017 ElEl ST_tbarW
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'ElEl>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tbarW/ElEl/
print 2017 ElEl ST_tW-NoFHad
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'ElEl>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tW-NoFHad/ElEl/
print 2017 ElEl ST_tbarW-NoFHad
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'ElEl>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tbarW-NoFHad/ElEl/
print 2017 ElEl ElEl_B
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__ElEl_B.txt' --filter 'ElEl>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ElEl_B/ElEl/
print 2017 ElEl ElEl_C
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__ElEl_C.txt' --filter 'ElEl>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ElEl_C/ElEl/
print 2017 ElEl ElEl_D
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__ElEl_D.txt' --filter 'ElEl>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ElEl_D/ElEl/
print 2017 ElEl ElEl_E
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__ElEl_E.txt' --filter 'ElEl>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ElEl_E/ElEl/
print 2017 ElEl ElEl_F
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__ElEl_F.txt' --filter 'ElEl>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ElEl_F/ElEl/
print 2017 Mu ST_tW
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_top_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'Mu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tW/Mu/
print 2017 Mu ST_tbarW
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'Mu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tbarW/Mu/
print 2017 Mu ST_tW-NoFHad
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'Mu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tW-NoFHad/Mu/
print 2017 Mu ST_tbarW-NoFHad
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'Mu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tbarW-NoFHad/Mu/
print 2017 Mu Mu_B
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__Mu_B.txt' --filter 'Mu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/Mu_B/Mu/
print 2017 Mu Mu_C
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__Mu_C.txt' --filter 'Mu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/Mu_C/Mu/
print 2017 Mu Mu_D
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__Mu_D.txt' --filter 'Mu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/Mu_D/Mu/
print 2017 Mu Mu_E
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__Mu_E.txt' --filter 'Mu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/Mu_E/Mu/
print 2017 Mu Mu_F
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__Mu_F.txt' --filter 'Mu>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/Mu_F/Mu/
print 2017 El ST_tW
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_top_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'El>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) == 0 && (ESV_TriggerAndLeptonLogic_selection & 64) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tW/El/
print 2017 El ST_tbarW
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'El>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) == 0 && (ESV_TriggerAndLeptonLogic_selection & 64) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tbarW/El/
print 2017 El ST_tW-NoFHad
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'El>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) == 0 && (ESV_TriggerAndLeptonLogic_selection & 64) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tW-NoFHad/El/
print 2017 El ST_tbarW-NoFHad
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'dbs:/ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/nmangane-NoveCampaign-31deb7c86682c648bf5094175e82e051/USER instance=prod/phys03' --filter 'El>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) == 0 && (ESV_TriggerAndLeptonLogic_selection & 64) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/ST_tbarW-NoFHad/El/
print 2017 El El_B
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__El_B.txt' --filter 'El>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) == 0 && (ESV_TriggerAndLeptonLogic_selection & 64) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/El_B/El/
print 2017 El El_C
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__El_C.txt' --filter 'El>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) == 0 && (ESV_TriggerAndLeptonLogic_selection & 64) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/El_C/El/
print 2017 El El_D
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__El_D.txt' --filter 'El>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) == 0 && (ESV_TriggerAndLeptonLogic_selection & 64) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/El_D/El/
print 2017 El El_E
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__El_E.txt' --filter 'El>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) == 0 && (ESV_TriggerAndLeptonLogic_selection & 64) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/El_E/El/
print 2017 El El_F
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2017__NANOv7_CorrNov__El_F.txt' --filter 'El>==>(ESV_TriggerAndLeptonLogic_selection & 24576) == 0 && (ESV_TriggerAndLeptonLogic_selection & 6144) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) == 0 && (ESV_TriggerAndLeptonLogic_selection & 64) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2017/El_F/El/
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__ElMu_A.txt' --filter 'ElMu>==>(ESV_TriggerAndLeptonLogic_selection & 20480) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/ElMu_A/ElMu/
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__ElMu_B.txt' --filter 'ElMu>==>(ESV_TriggerAndLeptonLogic_selection & 20480) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/ElMu_B/ElMu/
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__ElMu_C.txt' --filter 'ElMu>==>(ESV_TriggerAndLeptonLogic_selection & 20480) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/ElMu_C/ElMu/
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__ElMu_D.txt' --filter 'ElMu>==>(ESV_TriggerAndLeptonLogic_selection & 20480) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/ElMu_D/ElMu/
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__MuMu_A.txt' --filter 'MuMu>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/MuMu_A/MuMu/
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__MuMu_B.txt' --filter 'MuMu>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/MuMu_B/MuMu/
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__MuMu_C.txt' --filter 'MuMu>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/MuMu_C/MuMu/
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__MuMu_D.txt' --filter 'MuMu>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/MuMu_D/MuMu/
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__ElEl_A.txt' --filter 'ElEl>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/ElEl_A/ElEl/
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__ElEl_B.txt' --filter 'ElEl>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/ElEl_B/ElEl/
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__ElEl_C.txt' --filter 'ElEl>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/ElEl_C/ElEl/
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__ElEl_D.txt' --filter 'ElEl>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/ElEl_D/ElEl/
print 2018 Mu Mu_A
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__Mu_A.txt' --filter 'Mu>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 256) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/Mu_A/Mu/
print 2018 Mu Mu_B
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__Mu_B.txt' --filter 'Mu>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 256) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/Mu_B/Mu/
print 2018 Mu Mu_C
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__Mu_C.txt' --filter 'Mu>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 256) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/Mu_C/Mu/
print 2018 Mu Mu_D
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__Mu_D.txt' --filter 'Mu>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 256) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/Mu_D/Mu/
print 2018 El El_A
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__El_A.txt' --filter 'El>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 256) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/El_A/El/
print 2018 El El_B
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__El_B.txt' --filter 'El>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 256) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/El_B/El/
print 2018 El El_C
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__El_C.txt' --filter 'El>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 256) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/El_C/El/
print 2018 El El_D
python ~/Work/CMSSW_10_2_24_patch1/src/FourTopNAOD/RDF/scripts/nanoframe.py --input 'list:/eos/home-n/nmangane/analysis/LongTermFilelists/2018__NANOv7_CorrNov__El_D.txt' --filter 'El>==>(ESV_TriggerAndLeptonLogic_selection & 20480) == 0 && (ESV_TriggerAndLeptonLogic_selection & 2048) == 0 && (ESV_TriggerAndLeptonLogic_selection & 512) == 0 && (ESV_TriggerAndLeptonLogic_selection & 256) == 0 && (ESV_TriggerAndLeptonLogic_selection & 128) > 0' --simultaneous 4 --nThreads 8 --write --prefetch --redir root://cms-xrd-global.cern.ch//pnfs/iihe/cms --outdir /eos/user/n/nmangane/files/NANOv7_CorrNov/skims/2018/El_D/El/
